import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navbar from "@/app/components/navbar";

const poppins = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin", "latin-ext"] });

export const metadata: Metadata = {
    title: "Proto",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={poppins.className}>
            <Navbar/>
            {children}
        </body>
        </html>
    );
}
